sudo: required

services:
  - docker

before_install:
  - docker build -t lingfungc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true lingfungc/react-test npm test

after_success:
  - docker build -t lingfungc/fibonacci-client ./client
  - docker build -t lingfungc/fibonacci-server ./server
  - docker build -t lingfungc/fibonacci-worker ./worker
  - docker build -t lingfungc/fibonacci-nginx ./nginx

  # Login in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take those image and push them to Docker Hub
  - docker push lingfungc/fibonacci-client
  - docker push lingfungc/fibonacci-server
  - docker push lingfungc/fibonacci-worker
  - docker push lingfungc/fibonacci-nginx

deploy:
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "fibonacci-sequence"
  env: "Fibonacci-sequence-env"
  bucket_name: "elasticbeanstalk-eu-north-1-193654903449"
  bucket_path: "fibonacci-sequence"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
