name: Deploy Multi-Container App

on:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build test image
        run: docker build -t lingfungc/react-test -f ./client/Dockerfile.dev ./client

      - name: Run tests
        run: docker run -e CI=true lingfungc/react-test npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build production images
        run: |
          docker build -t lingfungc/fibonacci-client ./client
          docker build -t lingfungc/fibonacci-server ./server
          docker build -t lingfungc/fibonacci-worker ./worker
          docker build -t lingfungc/fibonacci-nginx ./nginx

      - name: Push images to Docker Hub
        run: |
          docker push lingfungc/fibonacci-client
          docker push lingfungc/fibonacci-server
          docker push lingfungc/fibonacci-worker
          docker push lingfungc/fibonacci-nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: fibonacci-sequence
          environment_name: Fibonacci-sequence-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-193654903449
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
